### ISSUE TITLE
Issue with loss and labels

### ISSUE THREAD

**Issue by jagadeesh09** [markdtw/tensorflow-queue-example#1]
Hi

Labels are getting shuffled during training. I am following the way you have written the code. Loss is not converging due to the labels problem. What could be the reason?

**Comment by markdtw** [comment]
Hi,

Sorry for the late reply, this repo is no longer maintained, if you are interested in playing with tensorflow APIs, you can check out this Gist I created. (it's pretty much just a cleaner version of tensorflow official tutorials)

https://gist.github.com/markdtw/ef1ec76e6be9104316c454455754af04

Thanks!

**Comment by jagadeesh09** [comment]
Thanks Mark! I will check that gist.
